apiVersion: v1
kind: Service
metadata:
  name: {{ include "mum.service.name" . | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
{{ include "mum.labels" . | indent 4 }}
spec:
  type: {{ .Values.mum.service.type }}
  ports:
    - port: {{ .Values.mum.service.port }}
      targetPort: {{ .Values.mum.deployment.container.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "mum.deployment.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name }}
