apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dovecot.pvc.name" . | quote }}
  namespace: {{ .Values.namespace | quote }}
  annotations:
    pv.beta.kubernetes.io/gid: "5000"
  labels:
    app.kubernetes.io/name: {{ include "dovecot.pvc.name" . | quote }}
{{ include "mum.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dovecot.persistentVolumeClaim.size }}