language: generic
fail_fast: true
install:
        - >
          curl -s -L https://get.helm.sh/helm-v2.15.2-linux-amd64.tar.gz
          | tar xzvf - --strip-components=1 linux-amd64/helm
        - chmod 0700 helm
        - echo -e "$GITHUB_SSH_KEY" | base64 -d > ~/.ssh/id_rsa
        - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        - chmod 0600 ~/.ssh/id_rsa
script:
        - set -e
        - mkdir -p out
        - eval "$(ssh-agent -s)"
        - ssh-add ~/.ssh/id_rsa
        - ./helm init --client-only
        - git clone --branch gh-pages git@github.com:AvesIT/Charts.git repo
        - ./helm package kube-plex -d repo -u
        - ./helm package kube-rclone -d repo -u
        - ./helm package longhorn -d repo -u
        - ./helm package mailu -d repo -u
        - ./helm package mariadb -d repo -u
        - ./helm package mum -d repo -u
        - ./helm package nextcloud -d repo -u
        - ./helm package redis -d repo -u
        - ./helm package roundcube -d repo -u
        - ./helm repo index --url https://avesit.github.io/Charts/ repo
        - cd repo
        - git add .
        - git commit -m "Travis build"
        - git push
