# Default values for mum.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: default

########
##
## Ingress Configuration
##

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    - secretName: tls-secret
      hosts:
      - minikube.local
  hosts:
  - host: minikube.local

########
##
## MUM Configuration
##

mum:
  deployment:
    name: mum
    replicaCount: 1
    image:
      repository: mumproject/mum
      tag: latest
      pullPolicy: Always
    container:
      port: 8080
  service:
    name: mum
    type: ClusterIP
    port: 8080

########
##
## Postfix Configuration
##

postfix:
  deployment:
    name: postfix
    replicaCount: 1
    image:
      repository: mumproject/postfix
      tag: latest
      pullPolicy: Always
    container:
      hostname: "example.local"
  service:
    name: postfix
    type: LoadBalancer

########
##
## Dovecot Configuration
##

dovecot:
  deployment:
    name: dovecot
    replicaCount: 1
    image:
      repository: mumproject/dovecot
      tag: latest
      pullPolicy: Always
  service:
    name: dovecot
    type: LoadBalancer
  internalService:
    name: dovecot-internal
    type: ClusterIP
  persistentVolumeClaim:
    name: dovecot-pv-claim
    size: 1Gi


########
##
## MariaDB Chart Configuration
##
## https://github.com/helm/charts/blob/master/stable/mariadb/values.yaml
##

mariadb:
  enabled: true
  replication:
    enabled: false
  existingSecret: 'db-secret'
  db:
    name: mum
    user: mum
  master:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 8Gi