apiVersion: v1
kind: Service
metadata:
  name: {{ include "postfix.service.name" . | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
{{ include "mum.labels" . | indent 4 }}
spec:
  type: {{ .Values.postfix.service.type }}
  ports:
  - { name: smtpd, port: 25, targetPort: 25, protocol: TCP }
  - { name: smtpssl, port: 465, targetPort: 465, protocol: TCP }
  - { name: smtp, port: 587, targetPort: 587, protocol: TCP }
  selector:
    app.kubernetes.io/name: {{ include "postfix.deployment.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name }}
